---
# tasks file for ether-channel
- name: Create ether channel {{ group_name }}
  cisco.ios.ios_lag_interfaces:
    config:
      - name: "{{ item.group_name }}"
        members: "{{ item.members }}"
  with_items: "{{ ether_channel_config }}"
  when: ether_channel_config is defined